### ISSUE TITLE
Incompatibility with ShadCN CLI

### ISSUE THREAD

**Issue by iamDyeus** [LuanRoger/electron-shadcn#139] opened 2024-12-29 17:09 UTC
I attempted to use the ShadCN CLI with the following command:

`npx shadcn@latest add button`

However, it appears that the current structure of this project is incompatible with the ShadCN CLI. If I have to manually add each component and hook from ShadCN UI, then this template doesn't seem useful for its intended purpose.

I suggest considering structural changes to the project to make it compatible with the ShadCN UI CLI, which would streamline the process and enhance usability.

**Comment by fernan2jr** [comment] 2024-12-30 13:09
Just tested this on a freshly cloned repository, and it works as expected.

![image](https://github.com/user-attachments/assets/f5ef9ffc-ee0f-440a-82e4-4917475be6f9)

**Comment by iamDyeus** [comment] 2024-12-30 14:57
Interesting, I'll try again with a new clone. 
if it works, I'll close this issue 👍🏻

**Comment by iamDyeus** [comment] 2024-12-31 06:36
@fernan2jr I made a fresh clone, and tried this command: 
`npx shadcn@latest add sidebar`
I get this output:
![image](https://github.com/user-attachments/assets/3a1f8268-f54e-4e4b-8df0-2dd78484de5a)
 its strange, since the file global.css is present there itself.

**Comment by fernan2jr** [comment] 2024-12-31 13:01
This does seem to be an issue. 
The directory and file are in the right place, and the aliases are set up and working. But for some reason, ShadCN isn't picking up Vite's configuration.

If you change `components.json` to use relative paths, the ShadCN CLI commands work fine.

![image](https://github.com/user-attachments/assets/92c6e140-3a38-4915-955f-8fc393b963dc)

**Comment by iamDyeus** [comment] 2024-12-31 14:08
Okay, so the error happens because `@/styles/global.css` is treated as a literal path instead of using the alias.
replacing the current `components.json` with this works just fine:

```json
{
    "$schema": "https://ui.shadcn.com/schema.json",
    "style": "default",
    "rsc": false,
    "tsx": true,
    "tailwind": {
        "config": "tailwind.config.js",
        "css": "src/styles/global.css",
        "baseColor": "slate",
        "cssVariables": true,
        "prefix": ""
    },
    "aliases": {
        "components": "@/components",
        "utils": "@/lib/utils"
    }
}

```

**Comment by iamDyeus** [comment] 2024-12-31 14:14
@LuanRoger Btw why is this a problem now? This commit was made back in January. 6dc64c549ec30a06818a2c8f6782ebf8b75abbc0
![image](https://github.com/user-attachments/assets/12cea8c4-3877-4bc5-956e-d576f0b7be31)

**Comment by LuanRoger** [comment] 2024-12-31 18:36
Hey! Thanks for open an issue and sorry for late response.

The "@" is an alias for `./src/*` defined in the `tsconfig.json`, and the shadcn CLI should resolve this alias just fine. I can't reproduce this error, I was able to install any component with the CLI.

If remove the "@" from "components.json" solves your problem, so you can keep that. As @fernan2jr point, this doesn't seems to be a common issue, so if you don't have any other information to share, you can close this issue.

**Closed** 2024-12-31 19:42 UTC
